#!/bin/bash

exec 2>&1

echo "Linking conf dirs"

mkdir -p {{pkg.svc_var_path}}/nginx/log
mkdir -p /hab/svc/nginx/var/

#ln -sf {{pkg.path}}/nginx/conf {{pkg.svc_var_path}}/
#ln -sf {{pkg.path}}/nginx/html {{pkg.svc_var_path}}/
