[http]
user = "hab"
worker_processes = 1
worker_connections = 1024
sendfile = "on"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = 60
gzip = "off"

[fpm]
user = "hab"
group = "hab"
max_children = 10
max_requests = 2048

